version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticdb
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=elasticsearch
      - ELASTIC_PASSWORD=DkIedPPSCb
      - ELASTIC_SECURITY=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.14.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=DkIedPPSCb
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
    driver_opts:
      device: ./esdata
      o: bind
      type: ntfs
